### ISSUE TITLE
Hard coded path to OpenSCAD and Windows specific code

### ISSUE THREAD

**Issue by VorpalBlade** [foreachthing/RecyclingSymbols#2]
`Recycling_Symbols.py` contains a hard coded path to OpenSCAD. It also uses the Windows specific `ntpath`. Both of these are issues for portability. 

It should be possible to replace `ntpath` with `os.path` (as `os.path` will be an alias to `ntpath` on Windows, and `posixpath` on Linux/Mac OS X).

As for the path to OpenSCAD I would prefer to pick it up from the `PATH` environment variable (that would work for me on Linux, but likely not for most Windows users). Maybe the user could provide the path to OpenSCAD as a command line argument?

**Comment by foreachthing** [comment]
Ok! I understand your request. I don't like that Windows/MacOS/Linux path disaster. But I'll look into it!
As for OpenSCAD path: command line would be the easiest (for me, at least 😉 ).

**Comment by foreachthing** [comment]
Please reopen if commit does not solve it for you.
